//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3.DbServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbClass", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class DbClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STableCatalogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STableSchemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STableTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STableCatalog {
            get {
                return this.STableCatalogField;
            }
            set {
                if ((object.ReferenceEquals(this.STableCatalogField, value) != true)) {
                    this.STableCatalogField = value;
                    this.RaisePropertyChanged("STableCatalog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STableName {
            get {
                return this.STableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.STableNameField, value) != true)) {
                    this.STableNameField = value;
                    this.RaisePropertyChanged("STableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STableScheme {
            get {
                return this.STableSchemeField;
            }
            set {
                if ((object.ReferenceEquals(this.STableSchemeField, value) != true)) {
                    this.STableSchemeField = value;
                    this.RaisePropertyChanged("STableScheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STableType {
            get {
                return this.STableTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.STableTypeField, value) != true)) {
                    this.STableTypeField = value;
                    this.RaisePropertyChanged("STableType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbServiceReference.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDbClassList", ReplyAction="http://tempuri.org/IDBService/GetDbClassListResponse")]
        ConsoleApp3.DbServiceReference.DbClass[] GetDbClassList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDbClassList", ReplyAction="http://tempuri.org/IDBService/GetDbClassListResponse")]
        System.Threading.Tasks.Task<ConsoleApp3.DbServiceReference.DbClass[]> GetDbClassListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : ConsoleApp3.DbServiceReference.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<ConsoleApp3.DbServiceReference.IDBService>, ConsoleApp3.DbServiceReference.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp3.DbServiceReference.DbClass[] GetDbClassList() {
            return base.Channel.GetDbClassList();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp3.DbServiceReference.DbClass[]> GetDbClassListAsync() {
            return base.Channel.GetDbClassListAsync();
        }
    }
}
