//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp320
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomeOrders_vw
    {
        public string AccountNumber { get; set; }
        public int SalesOrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public short OrderQty { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public decimal LineTotal { get; set; }
    }
}
