//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp320
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTimeStamp
    {
        public System.Guid GID { get; set; }
        public byte[] timeStampVersion { get; set; }
        public Nullable<int> rowNum { get; set; }
    }
}
