//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp320
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestChild1
    {
        public int IDcol { get; set; }
    
        public virtual TestIdent TestIdent { get; set; }
    }
}
