//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp314
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvertTest
    {
        public int ColId { get; set; }
        public byte[] ColTs { get; set; }
    }
}
