//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.MathServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathServiceReference.IMathServcice")]
    public interface IMathServcice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServcice/AddMethod", ReplyAction="http://tempuri.org/IMathServcice/AddMethodResponse")]
        int AddMethod(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathServcice/AddMethod", ReplyAction="http://tempuri.org/IMathServcice/AddMethodResponse")]
        System.Threading.Tasks.Task<int> AddMethodAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathServciceChannel : ConsoleApp1.MathServiceReference.IMathServcice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathServciceClient : System.ServiceModel.ClientBase<ConsoleApp1.MathServiceReference.IMathServcice>, ConsoleApp1.MathServiceReference.IMathServcice {
        
        public MathServciceClient() {
        }
        
        public MathServciceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServciceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServciceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServciceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddMethod(int x, int y) {
            return base.Channel.AddMethod(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddMethodAsync(int x, int y) {
            return base.Channel.AddMethodAsync(x, y);
        }
    }
}
