//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp349.GetDataTableService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDataTableService.IGetDataTableFromDB")]
    public interface IGetDataTableFromDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataTableFromDB/GetDataTableFromDBResult", ReplyAction="http://tempuri.org/IGetDataTableFromDB/GetDataTableFromDBResultResponse")]
        string GetDataTableFromDBResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataTableFromDB/GetDataTableFromDBResult", ReplyAction="http://tempuri.org/IGetDataTableFromDB/GetDataTableFromDBResultResponse")]
        System.Threading.Tasks.Task<string> GetDataTableFromDBResultAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataTableFromDBChannel : ConsoleApp349.GetDataTableService.IGetDataTableFromDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataTableFromDBClient : System.ServiceModel.ClientBase<ConsoleApp349.GetDataTableService.IGetDataTableFromDB>, ConsoleApp349.GetDataTableService.IGetDataTableFromDB {
        
        public GetDataTableFromDBClient() {
        }
        
        public GetDataTableFromDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataTableFromDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataTableFromDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataTableFromDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDataTableFromDBResult() {
            return base.Channel.GetDataTableFromDBResult();
        }
        
        public System.Threading.Tasks.Task<string> GetDataTableFromDBResultAsync() {
            return base.Channel.GetDataTableFromDBResultAsync();
        }
    }
}
