//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp349.StringGetLengthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringGetLengthService.IStringGetLength")]
    public interface IStringGetLength {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringGetLength/GetStringLengthResult", ReplyAction="http://tempuri.org/IStringGetLength/GetStringLengthResultResponse")]
        int GetStringLengthResult(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringGetLength/GetStringLengthResult", ReplyAction="http://tempuri.org/IStringGetLength/GetStringLengthResultResponse")]
        System.Threading.Tasks.Task<int> GetStringLengthResultAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringGetLengthChannel : ConsoleApp349.StringGetLengthService.IStringGetLength, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringGetLengthClient : System.ServiceModel.ClientBase<ConsoleApp349.StringGetLengthService.IStringGetLength>, ConsoleApp349.StringGetLengthService.IStringGetLength {
        
        public StringGetLengthClient() {
        }
        
        public StringGetLengthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringGetLengthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringGetLengthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringGetLengthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetStringLengthResult(string str) {
            return base.Channel.GetStringLengthResult(str);
        }
        
        public System.Threading.Tasks.Task<int> GetStringLengthResultAsync(string str) {
            return base.Channel.GetStringLengthResultAsync(str);
        }
    }
}
