//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp275.MathServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathServiceReference.IMathService")]
    public interface IMathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/AddMethod", ReplyAction="http://tempuri.org/IMathService/AddMethodResponse")]
        string AddMethod(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/AddMethod", ReplyAction="http://tempuri.org/IMathService/AddMethodResponse")]
        System.Threading.Tasks.Task<string> AddMethodAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/GetDBColumnString", ReplyAction="http://tempuri.org/IMathService/GetDBColumnStringResponse")]
        WcfServiceLibrary12.DBTables[] GetDBColumnString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/GetDBColumnString", ReplyAction="http://tempuri.org/IMathService/GetDBColumnStringResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary12.DBTables[]> GetDBColumnStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathServiceChannel : ConsoleApp275.MathServiceReference.IMathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathServiceClient : System.ServiceModel.ClientBase<ConsoleApp275.MathServiceReference.IMathService>, ConsoleApp275.MathServiceReference.IMathService {
        
        public MathServiceClient() {
        }
        
        public MathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddMethod(int x, int y) {
            return base.Channel.AddMethod(x, y);
        }
        
        public System.Threading.Tasks.Task<string> AddMethodAsync(int x, int y) {
            return base.Channel.AddMethodAsync(x, y);
        }
        
        public WcfServiceLibrary12.DBTables[] GetDBColumnString() {
            return base.Channel.GetDBColumnString();
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary12.DBTables[]> GetDBColumnStringAsync() {
            return base.Channel.GetDBColumnStringAsync();
        }
    }
}
