//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp351.ServerDataTableService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerDataTableService.IGetDataTable")]
    public interface IGetDataTable {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataTable/GetDataTable", ReplyAction="http://tempuri.org/IGetDataTable/GetDataTableResponse")]
        System.Data.DataTable GetDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataTable/GetDataTable", ReplyAction="http://tempuri.org/IGetDataTable/GetDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataTableChannel : ConsoleApp351.ServerDataTableService.IGetDataTable, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataTableClient : System.ServiceModel.ClientBase<ConsoleApp351.ServerDataTableService.IGetDataTable>, ConsoleApp351.ServerDataTableService.IGetDataTable {
        
        public GetDataTableClient() {
        }
        
        public GetDataTableClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataTableClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataTableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataTableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDataTable() {
            return base.Channel.GetDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync() {
            return base.Channel.GetDataTableAsync();
        }
    }
}
