//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp43.GetDBTableWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDBTableWCFService.IGetDBTable")]
    public interface IGetDBTable {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBTable/GetDataTable", ReplyAction="http://tempuri.org/IGetDBTable/GetDataTableResponse")]
        System.Data.DataTable GetDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBTable/GetDataTable", ReplyAction="http://tempuri.org/IGetDBTable/GetDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDBTableChannel : WpfApp43.GetDBTableWCFService.IGetDBTable, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDBTableClient : System.ServiceModel.ClientBase<WpfApp43.GetDBTableWCFService.IGetDBTable>, WpfApp43.GetDBTableWCFService.IGetDBTable {
        
        public GetDBTableClient() {
        }
        
        public GetDBTableClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDBTableClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBTableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBTableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDataTable() {
            return base.Channel.GetDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync() {
            return base.Channel.GetDataTableAsync();
        }
    }
}
