//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp297
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTotalOrdersByDay_vw
    {
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> TotalOrderQty { get; set; }
        public Nullable<decimal> TotalUnitPrice { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalSale { get; set; }
        public Nullable<long> TotalRows { get; set; }
    }
}
