//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp297
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSequence
    {
        public int SeqCol { get; set; }
    
        public virtual TestSeqChild1 TestSeqChild1 { get; set; }
        public virtual TestSeqChild2 TestSeqChild2 { get; set; }
    }
}
