//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp297
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestIdent
    {
        public int IDCol { get; set; }
    
        public virtual TestChild1 TestChild1 { get; set; }
        public virtual TestChild2 TestChild2 { get; set; }
    }
}
