//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ProductWCFServices")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SProduct", Namespace="http://schemas.datacontract.org/2004/07/ProductWCFServices.Model")]
    [System.SerializableAttribute()]
    public partial class SProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SFGFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SROPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSSLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SColor {
            get {
                return this.SColorField;
            }
            set {
                if ((object.ReferenceEquals(this.SColorField, value) != true)) {
                    this.SColorField = value;
                    this.RaisePropertyChanged("SColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SFGF {
            get {
                return this.SFGFField;
            }
            set {
                if ((object.ReferenceEquals(this.SFGFField, value) != true)) {
                    this.SFGFField = value;
                    this.RaisePropertyChanged("SFGF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLP {
            get {
                return this.SLPField;
            }
            set {
                if ((object.ReferenceEquals(this.SLPField, value) != true)) {
                    this.SLPField = value;
                    this.RaisePropertyChanged("SLP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMF {
            get {
                return this.SMFField;
            }
            set {
                if ((object.ReferenceEquals(this.SMFField, value) != true)) {
                    this.SMFField = value;
                    this.RaisePropertyChanged("SMF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SName {
            get {
                return this.SNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SNameField, value) != true)) {
                    this.SNameField = value;
                    this.RaisePropertyChanged("SName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SPID {
            get {
                return this.SPIDField;
            }
            set {
                if ((this.SPIDField.Equals(value) != true)) {
                    this.SPIDField = value;
                    this.RaisePropertyChanged("SPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPNO {
            get {
                return this.SPNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SPNOField, value) != true)) {
                    this.SPNOField = value;
                    this.RaisePropertyChanged("SPNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SROP {
            get {
                return this.SROPField;
            }
            set {
                if ((object.ReferenceEquals(this.SROPField, value) != true)) {
                    this.SROPField = value;
                    this.RaisePropertyChanged("SROP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSC {
            get {
                return this.SSCField;
            }
            set {
                if ((object.ReferenceEquals(this.SSCField, value) != true)) {
                    this.SSCField = value;
                    this.RaisePropertyChanged("SSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSSL {
            get {
                return this.SSSLField;
            }
            set {
                if ((object.ReferenceEquals(this.SSSLField, value) != true)) {
                    this.SSSLField = value;
                    this.RaisePropertyChanged("SSSL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProductStore.ServiceReference1.CompositeType GetDataUsingDataContract(ProductStore.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProductStore.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSProductByPID", ReplyAction="http://tempuri.org/IService1/GetSProductByPIDResponse")]
        ProductStore.ServiceReference1.SProduct[] GetSProductByPID(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSProductByPID", ReplyAction="http://tempuri.org/IService1/GetSProductByPIDResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> GetSProductByPIDAsync(int pID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProductStore.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProductStore.ServiceReference1.IService1>, ProductStore.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProductStore.ServiceReference1.CompositeType GetDataUsingDataContract(ProductStore.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProductStore.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ProductStore.ServiceReference1.SProduct[] GetSProductByPID(int pID) {
            return base.Channel.GetSProductByPID(pID);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> GetSProductByPIDAsync(int pID) {
            return base.Channel.GetSProductByPIDAsync(pID);
        }
    }
}
