//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ProductWCFServices")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SProduct", Namespace="http://schemas.datacontract.org/2004/07/ProductWCFServices.Model")]
    [System.SerializableAttribute()]
    public partial class SProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SDTMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SFGFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SLPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SMDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SMFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SPMIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SPSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SRGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SROPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SSCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SSEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SSSDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SSSLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSUMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SWUMCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SWeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SClass {
            get {
                return this.SClassField;
            }
            set {
                if ((object.ReferenceEquals(this.SClassField, value) != true)) {
                    this.SClassField = value;
                    this.RaisePropertyChanged("SClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SColor {
            get {
                return this.SColorField;
            }
            set {
                if ((object.ReferenceEquals(this.SColorField, value) != true)) {
                    this.SColorField = value;
                    this.RaisePropertyChanged("SColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SDD {
            get {
                return this.SDDField;
            }
            set {
                if ((this.SDDField.Equals(value) != true)) {
                    this.SDDField = value;
                    this.RaisePropertyChanged("SDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SDTM {
            get {
                return this.SDTMField;
            }
            set {
                if ((this.SDTMField.Equals(value) != true)) {
                    this.SDTMField = value;
                    this.RaisePropertyChanged("SDTM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SFGF {
            get {
                return this.SFGFField;
            }
            set {
                if ((this.SFGFField.Equals(value) != true)) {
                    this.SFGFField = value;
                    this.RaisePropertyChanged("SFGF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SLP {
            get {
                return this.SLPField;
            }
            set {
                if ((this.SLPField.Equals(value) != true)) {
                    this.SLPField = value;
                    this.RaisePropertyChanged("SLP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SMD {
            get {
                return this.SMDField;
            }
            set {
                if ((this.SMDField.Equals(value) != true)) {
                    this.SMDField = value;
                    this.RaisePropertyChanged("SMD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SMF {
            get {
                return this.SMFField;
            }
            set {
                if ((this.SMFField.Equals(value) != true)) {
                    this.SMFField = value;
                    this.RaisePropertyChanged("SMF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SName {
            get {
                return this.SNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SNameField, value) != true)) {
                    this.SNameField = value;
                    this.RaisePropertyChanged("SName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SPID {
            get {
                return this.SPIDField;
            }
            set {
                if ((this.SPIDField.Equals(value) != true)) {
                    this.SPIDField = value;
                    this.RaisePropertyChanged("SPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPL {
            get {
                return this.SPLField;
            }
            set {
                if ((object.ReferenceEquals(this.SPLField, value) != true)) {
                    this.SPLField = value;
                    this.RaisePropertyChanged("SPL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SPMID {
            get {
                return this.SPMIDField;
            }
            set {
                if ((this.SPMIDField.Equals(value) != true)) {
                    this.SPMIDField = value;
                    this.RaisePropertyChanged("SPMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPNO {
            get {
                return this.SPNOField;
            }
            set {
                if ((object.ReferenceEquals(this.SPNOField, value) != true)) {
                    this.SPNOField = value;
                    this.RaisePropertyChanged("SPNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SPSID {
            get {
                return this.SPSIDField;
            }
            set {
                if ((this.SPSIDField.Equals(value) != true)) {
                    this.SPSIDField = value;
                    this.RaisePropertyChanged("SPSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SRG {
            get {
                return this.SRGField;
            }
            set {
                if ((this.SRGField.Equals(value) != true)) {
                    this.SRGField = value;
                    this.RaisePropertyChanged("SRG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SROP {
            get {
                return this.SROPField;
            }
            set {
                if ((this.SROPField.Equals(value) != true)) {
                    this.SROPField = value;
                    this.RaisePropertyChanged("SROP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SSC {
            get {
                return this.SSCField;
            }
            set {
                if ((this.SSCField.Equals(value) != true)) {
                    this.SSCField = value;
                    this.RaisePropertyChanged("SSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SSED {
            get {
                return this.SSEDField;
            }
            set {
                if ((this.SSEDField.Equals(value) != true)) {
                    this.SSEDField = value;
                    this.RaisePropertyChanged("SSED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SSSD {
            get {
                return this.SSSDField;
            }
            set {
                if ((this.SSSDField.Equals(value) != true)) {
                    this.SSSDField = value;
                    this.RaisePropertyChanged("SSSD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SSSL {
            get {
                return this.SSSLField;
            }
            set {
                if ((this.SSSLField.Equals(value) != true)) {
                    this.SSSLField = value;
                    this.RaisePropertyChanged("SSSL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSUMC {
            get {
                return this.SSUMCField;
            }
            set {
                if ((object.ReferenceEquals(this.SSUMCField, value) != true)) {
                    this.SSUMCField = value;
                    this.RaisePropertyChanged("SSUMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSize {
            get {
                return this.SSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SSizeField, value) != true)) {
                    this.SSizeField = value;
                    this.RaisePropertyChanged("SSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SStyle {
            get {
                return this.SStyleField;
            }
            set {
                if ((object.ReferenceEquals(this.SStyleField, value) != true)) {
                    this.SStyleField = value;
                    this.RaisePropertyChanged("SStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWUMC {
            get {
                return this.SWUMCField;
            }
            set {
                if ((object.ReferenceEquals(this.SWUMCField, value) != true)) {
                    this.SWUMCField = value;
                    this.RaisePropertyChanged("SWUMC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SWeight {
            get {
                return this.SWeightField;
            }
            set {
                if ((this.SWeightField.Equals(value) != true)) {
                    this.SWeightField = value;
                    this.RaisePropertyChanged("SWeight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProductStore.ServiceReference1.CompositeType GetDataUsingDataContract(ProductStore.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProductStore.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSProductByPID", ReplyAction="http://tempuri.org/IService1/GetSProductByPIDResponse")]
        ProductStore.ServiceReference1.SProduct[] GetSProductByPID(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSProductByPID", ReplyAction="http://tempuri.org/IService1/GetSProductByPIDResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> GetSProductByPIDAsync(int pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveProducts", ReplyAction="http://tempuri.org/IService1/SaveProductsResponse")]
        ProductStore.ServiceReference1.SProduct[] SaveProducts(ProductStore.ServiceReference1.SProduct[] sProductList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveProducts", ReplyAction="http://tempuri.org/IService1/SaveProductsResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> SaveProductsAsync(ProductStore.ServiceReference1.SProduct[] sProductList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSelectedProduct", ReplyAction="http://tempuri.org/IService1/UpdateSelectedProductResponse")]
        ProductStore.ServiceReference1.SProduct[] UpdateSelectedProduct(ProductStore.ServiceReference1.SProduct selectedSProd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSelectedProduct", ReplyAction="http://tempuri.org/IService1/UpdateSelectedProductResponse")]
        System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> UpdateSelectedProductAsync(ProductStore.ServiceReference1.SProduct selectedSProd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProductStore.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProductStore.ServiceReference1.IService1>, ProductStore.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProductStore.ServiceReference1.CompositeType GetDataUsingDataContract(ProductStore.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ProductStore.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ProductStore.ServiceReference1.SProduct[] GetSProductByPID(int pID) {
            return base.Channel.GetSProductByPID(pID);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> GetSProductByPIDAsync(int pID) {
            return base.Channel.GetSProductByPIDAsync(pID);
        }
        
        public ProductStore.ServiceReference1.SProduct[] SaveProducts(ProductStore.ServiceReference1.SProduct[] sProductList) {
            return base.Channel.SaveProducts(sProductList);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> SaveProductsAsync(ProductStore.ServiceReference1.SProduct[] sProductList) {
            return base.Channel.SaveProductsAsync(sProductList);
        }
        
        public ProductStore.ServiceReference1.SProduct[] UpdateSelectedProduct(ProductStore.ServiceReference1.SProduct selectedSProd) {
            return base.Channel.UpdateSelectedProduct(selectedSProd);
        }
        
        public System.Threading.Tasks.Task<ProductStore.ServiceReference1.SProduct[]> UpdateSelectedProductAsync(ProductStore.ServiceReference1.SProduct selectedSProd) {
            return base.Channel.UpdateSelectedProductAsync(selectedSProd);
        }
    }
}
