//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.GetSODListServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/WcfService11.Model")]
    [System.SerializableAttribute()]
    public partial class SalesOrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierTrackingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesOrderDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpecialOfferIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierTrackingNumber {
            get {
                return this.CarrierTrackingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierTrackingNumberField, value) != true)) {
                    this.CarrierTrackingNumberField = value;
                    this.RaisePropertyChanged("CarrierTrackingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short OrderQty {
            get {
                return this.OrderQtyField;
            }
            set {
                if ((this.OrderQtyField.Equals(value) != true)) {
                    this.OrderQtyField = value;
                    this.RaisePropertyChanged("OrderQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesOrderDetailID {
            get {
                return this.SalesOrderDetailIDField;
            }
            set {
                if ((this.SalesOrderDetailIDField.Equals(value) != true)) {
                    this.SalesOrderDetailIDField = value;
                    this.RaisePropertyChanged("SalesOrderDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesOrderID {
            get {
                return this.SalesOrderIDField;
            }
            set {
                if ((this.SalesOrderIDField.Equals(value) != true)) {
                    this.SalesOrderIDField = value;
                    this.RaisePropertyChanged("SalesOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpecialOfferID {
            get {
                return this.SpecialOfferIDField;
            }
            set {
                if ((this.SpecialOfferIDField.Equals(value) != true)) {
                    this.SpecialOfferIDField = value;
                    this.RaisePropertyChanged("SpecialOfferID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPriceDiscount {
            get {
                return this.UnitPriceDiscountField;
            }
            set {
                if ((this.UnitPriceDiscountField.Equals(value) != true)) {
                    this.UnitPriceDiscountField = value;
                    this.RaisePropertyChanged("UnitPriceDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetSODListServiceReference.IGetSODList")]
    public interface IGetSODList {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSODList/GetSODSList", ReplyAction="http://tempuri.org/IGetSODList/GetSODSListResponse")]
        ConsoleApp1.GetSODListServiceReference.SalesOrderDetail[] GetSODSList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetSODList/GetSODSList", ReplyAction="http://tempuri.org/IGetSODList/GetSODSListResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.GetSODListServiceReference.SalesOrderDetail[]> GetSODSListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetSODListChannel : ConsoleApp1.GetSODListServiceReference.IGetSODList, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSODListClient : System.ServiceModel.ClientBase<ConsoleApp1.GetSODListServiceReference.IGetSODList>, ConsoleApp1.GetSODListServiceReference.IGetSODList {
        
        public GetSODListClient() {
        }
        
        public GetSODListClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetSODListClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSODListClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetSODListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp1.GetSODListServiceReference.SalesOrderDetail[] GetSODSList() {
            return base.Channel.GetSODSList();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.GetSODListServiceReference.SalesOrderDetail[]> GetSODSListAsync() {
            return base.Channel.GetSODSListAsync();
        }
    }
}
