//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp44.GetDBTableService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDBTableService.IGetDBTables")]
    public interface IGetDBTables {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBTables/GetDBDataTables", ReplyAction="http://tempuri.org/IGetDBTables/GetDBDataTablesResponse")]
        System.Data.DataTable GetDBDataTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBTables/GetDBDataTables", ReplyAction="http://tempuri.org/IGetDBTables/GetDBDataTablesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDBDataTablesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDBTablesChannel : WpfApp44.GetDBTableService.IGetDBTables, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDBTablesClient : System.ServiceModel.ClientBase<WpfApp44.GetDBTableService.IGetDBTables>, WpfApp44.GetDBTableService.IGetDBTables {
        
        public GetDBTablesClient() {
        }
        
        public GetDBTablesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDBTablesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBTablesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBTablesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDBDataTables() {
            return base.Channel.GetDBDataTables();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDBDataTablesAsync() {
            return base.Channel.GetDBDataTablesAsync();
        }
    }
}
