//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp349.ToUpperServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToUpperServiceWCF.IToUpperService")]
    public interface IToUpperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToUpperService/StringToUpper", ReplyAction="http://tempuri.org/IToUpperService/StringToUpperResponse")]
        string StringToUpper(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToUpperService/StringToUpper", ReplyAction="http://tempuri.org/IToUpperService/StringToUpperResponse")]
        System.Threading.Tasks.Task<string> StringToUpperAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToUpperServiceChannel : ConsoleApp349.ToUpperServiceWCF.IToUpperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToUpperServiceClient : System.ServiceModel.ClientBase<ConsoleApp349.ToUpperServiceWCF.IToUpperService>, ConsoleApp349.ToUpperServiceWCF.IToUpperService {
        
        public ToUpperServiceClient() {
        }
        
        public ToUpperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToUpperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToUpperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToUpperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StringToUpper(string str) {
            return base.Channel.StringToUpper(str);
        }
        
        public System.Threading.Tasks.Task<string> StringToUpperAsync(string str) {
            return base.Channel.StringToUpperAsync(str);
        }
    }
}
